name: Global workflow to rule them all

on:
  push:
      branches: [ master ] #or main

jobs:

  replicate_changes:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Replicating global workflow
          uses: derberg/global-workflows-support@v0.0.2
          with:
            github_token: ${{ secrets.CUSTOM_TOKEN }}
            files_to_ignore: update-workflows.yml
            repos_to_ignore: Twitch-Watcher
            exclude_private: true
            committer_username: workflow updater
            committer_email: ci-job@maintaina.com
            commit_message: "ci: update global workflows"
